version: '3.8'

services:
  php-apache:
    container_name: test-php-apache
    build:
      dockerfile: Dockerfile
      context: ./docker
    volumes:
      - .:/var/www/html
    ports:
      - 81:80
  mysql:
    container_name: test-mysql
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1qazxsw2
      MYSQL_DATABASE: testdb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "9907:3306"
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    depends_on:
      - mysql
    container_name: test-phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - 8080:80
###> doctrine/doctrine-bundle ###
  database:
    image: postgres:${POSTGRES_VERSION:-15}-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-app}
      # You should definitely change the password in production
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-!ChangeMe!}
      POSTGRES_USER: ${POSTGRES_USER:-app}
    volumes:
      - database_data:/var/lib/postgresql/data:rw
      # You may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
      # - ./docker/db/data:/var/lib/postgresql/data:rw
###< doctrine/doctrine-bundle ###

volumes:
###> doctrine/doctrine-bundle ###
  database_data:
###< doctrine/doctrine-bundle ###
